#!/usr/bin/env bash
cd ~/
pad=$1
Array=("*.jpg" "*.png")
cd $pad
if [ -d Afbeeldingen ]; then
	echo "Map: 'Afbeeldingen' bestaat al."
else
	mkdir Afbeeldingen
	echo "Map 'Afbeeldingen' aangemaakt."
fi

for item in ${Array[@]}; do
	find -maxdepth 1 -name $item -exec mv {} Afbeeldingen/{} ';'
done

