#!/usr/bin/env bash
files=$(find $1 -maxdepth 1 -type f)

type1Count=0
type2Count=0
type3Count=0
type4Count=0

for file in $files; do
    case $file in
	*$2)
	((type1Count+=1))
	;;
	*$3)
	((type2Count+=1))
	;;
	*$4)
	((type3Count+=1))
	;;
	*$5)
	((type4Count+=1))
	;;
	*)
	echo "Geef niet meer dan 4 bestandstypen mee"
	;;
    esac
done

case $# in
    2)
	echo aantal $2 bestanden:	$type1Count
    ;;
    3)
	echo aantal $2 bestanden:	$type1Count
	echo aantal $3 bestanden:	$type2Count
    ;;
    4)
	echo aantal $2 bestanden:	$type1Count
	echo aantal $3 bestanden:	$type2Count
	echo aantal $4 bestanden:	$type3Count
    ;;
    *)
	echo aantal $2 bestanden:     $type1Count
	echo aantal $3 bestanden:     $type2Count
	echo aantal $4 bestanden:     $type3Count
	echo aantal $5 bestanden:     $type4Count
    ;;
esac
